export enum payout {
    PAYOUT_DECLINED = 'P-100',
    PAYOUT_ABORTED = 200,
    PAYOUT_NOT_STARTING = 300,
}

export enum buyerDeposit {
    INITIALIZE_PAYSTACK_FAIL = 100,
    USER_ACCOUNT_VERIFICATION_FAIL = 200,
    CHARGE_DECLINED = 300,
}

